= plumb unit

image:https://travis-ci.org/multimediabs/plumb_unit.svg?branch=master[Build Status,link=https://travis-ci.org/multimediabs/plumb_unit]

Plumb unit creates roles with testing framework or adds testing framework to existing role.

Place yourself in the root dir of your roles and launch:

 /path/to/plumb_unit/ansible_make_new_tested_role my-new-role

This will create a _roles_ directory in which the _my_new_role_ is created. The role itself only contains an empty tasks/main.yml and a tests directory.

== Prerequisites
* link:view-source:https://docker.io[docker]
* link:view-source:https://www.nist.gov/services-resources/software/expect[expect]

== Using default testing environment

To run tests for your role, you can then go to the tests directory and run them:

 cd roles/my-new-role/tests
 ./run_tests.sh

This exemple will run tests in a centos6 container. It will run all tests found in files named _test_my-new-role*_centos6_.

== specifying distribution and version

To run test on a specific distribution, make a link for run_tests.sh ending with _distribution:

 ln -s run_tests.sh run_tests_jessie.sh
 ./run_tests_jessie.sh

This will run tests in _test_my-new-role*_jessie_.

== cluster tests

cluster tests will be run by adding _cluster suffix to link and tests files:

 ln -s run_tests.sh run_tests_jessie_cluster.sh
 ./run_tests_jessie_cluster.sh

This will run tests in _test_my-new-role*_jessie_cluster_.

Note that in this particular mode, tests are played from outside the containers. Tests then needs _docker exec_ commands to access the container and check things within.
