#!/bin/bash

test_dockerfile_archlinux_runs_archlinux() {
  assert 'expect -d <<EOF
set timeout 10
log_user 0
spawn ./run_tests_archlinux.sh -d
expect {
  timeout { send_user "Failed to get prompt\n"; exit 1 }
  eof { send_user "Failed to launch docker \n"; exit 1 }
  -re ".root@.* tests.# .*"
}
send "cat /etc/issue\n"
expect {
  timeout { send_user "Did not match archlinux version\n"; exit 1 }
  "Arch Linux"
}
send "exit\n"
expect "exit"
EOF
'
}

setup() {
  test_prefix=test_ # workaround for bash_unit not to try to run this test on first pass
  cat > test_plumb_unit_archlinux <<EOF
#!/bin/bash
EOF
  ln -s run_tests.sh run_tests_archlinux.sh
}

teardown() {
  rm test_plumb_unit_archlinux
  rm run_tests_*.sh 2>/dev/null
}

assert "expect -v" "expect needs to be installed to run this tests"
