#!/bin/bash

test_python_versionn_is_2_7() {
  assert "./run_tests_centos6.sh -p python_2_7 test_plumb_unit_centos6"
}

test_dockerfile_centos6_runs_centos_6() {
  assert 'expect -d <<EOF
set timeout 10
log_user 0
spawn ./run_tests_centos6.sh -d
expect {
  timeout { send_user "Failed to get prompt\n"; exit 1 }
  eof { send_user "Failed to launch docker \n"; exit 1 }
  -re ".root@.* /.# .*"
}
send "cat /etc/issue.net\n"
expect {
  timeout { send_user "Did not match debian version\n"; exit 1 }
  "CentOS release 6"
}
send "exit\n"
expect "exit"
EOF
'
}

setup() {
  test_prefix=test_ # workaround for bash_unit not to try to run this test on first pass
  cat > test_plumb_unit_centos6 <<EOF
#!/bin/bash
${test_prefix}python_2_7() { assert "python -V | grep ' 2\.7'" "oups"; }
EOF
  ln -s run_tests.sh run_tests_centos6.sh
}

teardown() {
  rm test_plumb_unit_centos6
  rm run_tests_*.sh 2>/dev/null
}

assert "expect -v" "expect needs to be installed to run this tests"

